version: 2 #circleci 2.0
jobs: # basic unit of work in a run
  first-break: #break the build
    docker:
      - image: gcr.io/google-appengine/nodejs #docker image which is built to boot up a container - virtual machine where languages/system utililies/dependencies/webbrowser/tools that project need to run
    steps:
      - checkout
      - run: echo "HELLO WORLD"
  #main build
  second-break:
    docker:
      - image: gcr.io/google-appengine/nodejs #docker image matched this project
    steps:
      - checkout
      - restore_cache: # restore the cache of dependencies
          keys:
            - v1-repos-{{ checksum "yarn.lock" }}
            - v1-repos
      - run:
          command: | # | will add if have multiple commands
            yarn install --production=false #production=false allows install devDependencies packages
      - save_cache:
          paths:
            - ~/.cache/yarn #path of saving-restoring cache
          key: v1-repos-{{ checksum "yarn.lock" }}
      - run:
          command:
            yarn lint
workflows: #usually put on top or bottom of file
  version: 2
  breaks: #named whatever i want to be
    jobs:
      - first-break #name of each break
      - second-break
