version: 2 #circleci 2.0
jobs: # basic unit of work in a run
  build:
    docker:
      - image: gcr.io/google-appengine/nodejs #docker image matched this project
    steps:
      - checkout
      - run:
          command: | # | will add if have multiple commands
            yarn install --production=false #production=false allows install devDependencies packages
      - run:
          command:
            yarn lint
workflows: #usually put on top or bottom of file
  version: 2
  breaks: #named whatever i want to be
    jobs:
      - build
